mode: train
lmdb: False
dry_run: false
dataset_root_rgb: './datasets'
dataset_json_folder: '/mnt/ssd/datasets/deepfake/dataset_json/'
dataset_type: 'verihubs'
SWA: False
save_avg: True
log_dir: ./logs/training/
nEpochs: 20
train_batchSize: 24
test_batchSize: 24
train_dataset : [
    test_200k_24nov_merged_train
    #test_200k_merged_train
    #test_200k_train,
    #test_200k_swapped_train,
    #200k_live_face_dataset_55plus,
    #result_blendface-strictpose,
    #result_inswapper-strictpose,
    #result_mobilefaceswap-strictpose,
    #result_reswapper-strictpose
    #result_e4s_20251103-strictpose
]
test_dataset : [
    test_200k_24nov_merged_test
    #test_200k_merged_train
    #test_200k_test,
    #test_200k_swapped_test
    #200k_live_face_dataset_55plus,
    #result_e4s_20251103-strictpose
]
dataset_percentage : {
    200k_live_face_dataset: 1.0,
    result_e4s_20251103: 1.0
}
# label settings
label_dict:
  # DFD
  DFD_fake: 1
  DFD_real: 0
  # FF++ + FaceShifter(FF-real+FF-FH)
  FF-SH: 1
  FF-F2F: 1
  FF-DF: 1
  FF-FS: 1
  FF-NT: 1
  FF-FH: 1
  FF-real: 0
  # CelebDF
  CelebDFv1_real: 0
  CelebDFv1_fake: 1
  CelebDFv2_real: 0
  CelebDFv2_fake: 1
  # DFDCP
  DFDCP_Real: 0
  DFDCP_FakeA: 1
  DFDCP_FakeB: 1
  # DFDC
  DFDC_Fake: 1
  DFDC_Real: 0
  # DeeperForensics-1.0
  DF_fake: 1
  DF_real: 0
  # UADFV
  UADFV_Fake: 1
  UADFV_Real: 0
  # Roop
  roop_Real: 0
  roop_Fake: 1